title: vianu
description: an open-source platform for the life sciences
theme: just-the-docs

url: https://open-vianu.github.io/vianu

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template